# Generated by Django 5.0.3 on 2024-05-22 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_alter_banner_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='deal',
            name='url',
            field=models.URLField(default='http://breadfruit.me'),
        ),
    ]
