# Generated by Django 5.0.3 on 2024-05-22 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_deal_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deal',
            name='url',
            field=models.URLField(),
        ),
    ]
